apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    certificatesResolvers:
      letsencrypt:
        acme:
          email: dafandikri@gmail.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web

    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https

    persistence:
      enabled: true
      storageClass: local-path
      path: /data
      size: 128Mi
